# See   https://kubernetes.io/docs/api-reference/v1.6/
#       https://kubernetes.io/docs/api-reference/v1.6/#deployment-v1beta1-apps
#

# webapi app
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    product: k8s-demo
  name: webapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapi
        product: k8s-demo 
    spec:
      containers:
      - name: webapi 
        image: pmcgrath/webapi:1.1
        imagePullPolicy: Always
        env:
          - name: AWS_REGION
            value: eu-west-1
        livenessProbe:
          httpGet:
            path: /health
            port: 5000 
            scheme: HTTP
          initialDelaySeconds: 5 
          timeoutSeconds: 5 
        ports:
          - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 30Mi
