apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    product: k8s-demo
  name: webapi
data:
  appsettings.json: |
    {
      "store": {
        "type": "InMemory",
        "connectionString": "webapi-redis-store:6379"
      },
    }
