# See   https://kubernetes.io/docs/api-reference/v1.6/
#       https://kubernetes.io/docs/api-reference/v1.6/#service-v1-core
#

# webapi service
apiVersion: v1
kind: Service
metadata:
  labels:
    product: k8s-demo
  name: webapi
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: webapi
  type: LoadBalancer
