# See   https://kubernetes.io/docs/api-reference/v1.7/
#       https://kubernetes.io/docs/api-reference/v1.7/#job-v1-batch

apiVersion: batch/v1
kind: Job
metadata:
  name: job-demo
spec:
  template:
    metadata:
      name: job-demo
    spec:
      containers:
      - name: job-demo-1 
        image: busybox:latest
        command: ["/bin/sh"]
        args: ["-c", "seq=1; while [[ $seq != 10 ]]; do echo $(date) $seq Still working...; sleep 10s; let seq=$((seq + 1)); done"]
      restartPolicy: Never
