apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    product: k8s-demo
  name: demo
data:
  settings.json: |
    {
      "store": {
        "type": "InMemory",
    }

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    product: k8s-demo
  name: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
        product: k8s-demo
    spec:
      containers:
        - name: demo
          image: pmcgrath/shellloop:1
          imagePullPolicy: Always
          volumeMounts:
            - name: demo-config
              mountPath: /app
              subPath: settings.json
      volumes:
        - name: demo-config
          configMap:
            name: demo
